Update short_description.txt
AdAway/AdAway pull request #2603
Opened 2021-03-13 10:09 UTC by GermanGospel

The F-Droid app cuts of the old German text version: "AdAway ist ein Open-Source-Werbeblocker für Android, der die Hosts-Datei verwend" - the string should end with "verwendet." - I shortened the text to fix this. (I used the github website to submit this change. I don't manually named the branch.)

2021-03-13 10:17 UTC, GermanGospel commented
https://f-droid.org/packages/org.adaway/ cuts of the old text - after the same number if characters.

2021-03-13 10:19 UTC, GermanGospel commented
@PerfectSlayer - Do I have to create an issue first or can such little changes made without this overhead?

2021-03-22 07:45 UTC, Vankog requested changes
Thanks for bringing this to our attention.
It seems the SHort description has a character limit that hits several translations.

Unfortunately, merging this PR would be of no avail in the long run. 
Transifex is the single source of all our translations, we need to change it there in order to persist it in the code base.

I'll trigger that!

Thank you, nontheless!

2021-03-22 07:50 UTC, Vankog commented
Alright, I just saw that you changed it there already, thanks!

2021-03-22 08:15 UTC, closed without merging

2021-03-22 08:16 UTC, Vankog commented
DE fixed in #2622